export const CREATE_WORK_POST = "CREATE_WORK_POST";
export const CREATE_INFORMAL_POST = "CREATE_INFORMAL_POST";
export const DELETE_WORK_POST = "DELETE_WORK_POST";
export const DELETE_INFORMAL_POST = "DELETE_INFORMAL_POST";
export const REDACT_WORK_POST = "REDACT_WORK_POST";
export const REDACT_INFORMAL_POST = "REDACT_INFORMAL_POST";
export const CURR_PATH = "CURR_PATH";
